### ISSUE TITLE
[QST] Is get_event()'s thread_local problematic?

### ISSUE THREAD

**Issue by jiajunchang** [rapidsai/rmm#1306] opened 2023-07-21 04:55 UTC
https://github.com/rapidsai/rmm/blob/0a5b86cf9958dc195fb70e63e83095f0aa8b33c5/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L288

```c++
stream_event_pair get_event(cuda_stream_view stream)
{
    if (stream.is_per_thread_default()) {
      // Create a thread-local shared event wrapper. Shared pointers in the thread and in each MR
      // instance ensures it is destroyed cleaned up only after all are finished with it.
      thread_local auto event_tls = std::make_shared<event_wrapper>();
      default_stream_events.insert(event_tls);
      return stream_event_pair{stream.value(), event_tls->event};
    }
...
```

For the above code, the thread_local will make the `event_tls` a thread static varible. I think the `event_tls` will be invalid if the thread switches the device it's working on.

Thinking of the code below, I got an assertion failure caused by `cudaEventRecord` when destructing `b`. According to [Stream synchronization behavior](https://docs.nvidia.com/cuda/cuda-runtime-api/stream-sync-behavior.html#stream-sync-behavior), "per-thread default stream is an implicit stream local to both the thread and the CUcontext", so I assume the two `cuda_stream_per_thread` should refer to different streams on each device, please correct me if it's wrong.

BTW, it doesn't matter whether it's in PTDS build or not, as long as I'm using `cuda_stream_per_thread`, the assertion failure occurs.

```c++
// initializing pool_memory_resource of multiple devices
...
{
    cudaSetDevice(0);
    rmm::device_uvector<int> a(10, rmm::cuda_stream_per_thread);

    {
        cudaSetDevice(1);
        rmm::device_uvector<int> b(10, rmm::cuda_stream_per_thread);
    }

    cudaSetDevice(0);
}
```

Is this a bug or an intended behavior. If it's an intended behavior, then is it true that in general I shouldn't let the thread switch devices when working with rmm, though I didn't see any  documented restriction about that, maybe I missed something.

**Comment by harrism** [comment] 2023-07-26 11:41
We will need to look at this. A device memory resource is only valid on a single device. So you would need to create two MRs and pass the correct one explicitly to each device_vector constructor.

**Comment by jiajunchang** [comment] 2023-07-27 01:53
> We will need to look at this. A device memory resource is only valid on a single device. So you would need to create two MRs and pass the correct one explicitly to each device_vector constructor.

In fact I did initialize pool mrs and use `set_per_device_resource` for each device, which is skipped in the code I provided though, as commented "// initializing pool_memory_resource of multiple devices". Then device_uvector will call `get_current_device_resource` to get the correct one. I'll provide the whole code below just to clarify.

```c++
using MemoryResource = rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource>;

rmm::mr::cuda_memory_resource general_mr;

// initializing pool_memory_resource of multiple devices
int devices      = 2;
size_t pool_size = 10240;
std::vector<std::shared_ptr<MemoryResource>> mrs;

for (int i = 0; i < devices; ++i) {
    cudaSetDevice(i);
    auto mr = std::make_shared<MemoryResource>(&general_mr, pool_size, pool_size);
    rmm::mr::set_per_device_resource(rmm::cuda_device_id{i}, mr.get());
    mrs.emplace_back(mr);
}

{
    cudaSetDevice(0);
    rmm::device_uvector<int> a(10, rmm::cuda_stream_per_thread, mrs[0].get());

    {
        cudaSetDevice(1);
        rmm::device_uvector<int> b(10, rmm::cuda_stream_per_thread, mrs[1].get());
        // Destructing `b` cause:  CUDA Error detected. cudaErrorInvalidResourceHandle invalid resource handle
    }

    cudaSetDevice(0);
}
```

**Comment by harrism** [comment] 2023-08-30 00:40
I created a test with your code above and ran it on a DGX H100 and got no error. Can you provide more information on how to reproduce the problem?

**Comment by jiajunchang** [comment] 2023-08-30 02:49
@harrism I was using rmm-23.06, fmt-9.1.0, spdlog-1.11.0. I created a "main.cu" and put my code into the main() function. I used this compile command:
`nvcc -std=c++17 -DFMT_HEADER_ONLY -I rmm/include -I fmt/include -I spdlog/include main.cu -o main`

I tested it on 2 machines, `nvcc-11.4 4-K80` and `nvcc-11.5 2-P40`, both reproduced the error.

**Comment by harrism** [comment] 2023-08-30 07:15
Any chance you can try with CUDA 12? It will take me some effort to set up an older version.

**Comment by wence-** [comment] 2023-08-30 09:52
I can also repro on both cuda 11.8 and 12.2. I think this is a bug in how RMM manages events. But it is probably slightly fiddly to check.

The problem is due to this restriction mentioned in the [`cudaEventRecord` docs](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__EVENT.html#group__CUDART__EVENT_1gf4fcb74343aa689f4159791967868446) (emphasis mine):

> Captures in `event` the contents of `stream` at the time of this call. **`event` and `stream` must be on the same CUDA context.**

So this is a place where implicit contexts leak from the driver into the runtime API in a hard-to-track way. This restriction means that the following pattern does not result in a useful event (we can never call `eventrecord` on it):

```c
#include <cuda_runtime.h>

int main(void)
{
  cudaStream_t stream;
  cudaEvent_t event;
  cudaSetDevice(0);
  cudaStreamCreate(&stream);
  cudaSetDevice(1);
  cudaEventCreate(&event);
  cudaEventRecord(event, stream); // uh-oh, event and stream not on same context
  return 0;
}
```

Indeed, running under compute-sanitizer:
```
========= COMPUTE-SANITIZER
========= Program hit cudaErrorInvalidResourceHandle (error 400) due to "invalid resource handle" on CUDA API call to cudaEventRecord.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x441846]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:cudaEventRecord [0x6f8d5]
=========                in /home/wence/Documents/src/doodles/c++/rmm-bug/./a.out
=========     Host Frame:main [0xabfd]
=========                in /home/wence/Documents/src/doodles/c++/rmm-bug/./a.out
=========     Host Frame:../sysdeps/nptl/libc_start_call_main.h:58:__libc_start_call_main [0x29d90]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:../csu/libc-start.c:379:__libc_start_main [0x29e40]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:_start [0xaac5]
=========                in /home/wence/Documents/src/doodles/c++/rmm-bug/./a.out
========= 
========= ERROR SUMMARY: 1 error
```

So this suggests that it is not just due to the thread local storage that we might have a problem, any time an `eventRecord` is called with a mismatching stream/context pair active, we can have problems.

For example, here's some code that runs fine (and I think follows all the cuda runtime semantics) when using `rmm::mr::cuda_memory_resource`, but is no longer valid when using the pool.

```c++
#include <cstddef>
#include <memory>
#include <rmm/cuda_stream.hpp>
#include <rmm/cuda_stream_view.hpp>
#include <rmm/device_uvector.hpp>
#include <rmm/mr/device/cuda_memory_resource.hpp>
#include <rmm/mr/device/per_device_resource.hpp>
#include <rmm/mr/device/pool_memory_resource.hpp>
#include <vector>

int main(void) {
#ifdef USE_POOL
  using MemoryResource =
      rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource>;

  rmm::mr::cuda_memory_resource general_mr;
#else
  using MemoryResource = rmm::mr::cuda_memory_resource;
#endif
  // initializing pool_memory_resource of multiple devices
  int devices = 2;
  std::size_t pool_size = 10240;
  std::vector<std::shared_ptr<MemoryResource>> mrs;

  for (int i = 0; i < devices; ++i) {
    cudaSetDevice(i);
#ifdef USE_POOL
    auto mr = std::make_shared<MemoryResource>(&general_mr, pool_size, pool_size);
#else
    auto mr = std::make_shared<rmm::mr::cuda_memory_resource>();
#endif
    rmm::mr::set_per_device_resource(rmm::cuda_device_id{i}, mr.get());
    mrs.emplace_back(mr);
  }

  {
    cudaSetDevice(0);
    rmm::device_uvector<int> a(10, rmm::cuda_stream_default, mrs[0].get());
    {
      cudaSetDevice(1);
      rmm::device_uvector<int> b(20, rmm::cuda_stream_default, mrs[1].get());
    }
    // Forgot to switch back to device zero, so ~a() will run with
    // context corresponding to device one active.
    // This is a no-no for the event record in the pool deallocation
    // cudaSetDevice(0);
  }
  return 0;
}
```

```sh
$ nvcc -g -O0 -std=c++17 -DFMT_HEADER_ONLY -I $HOME/Documents/src/rapids/rmm/include/ -I $HOME/Documents/src/rapids/compose/etc/conda/cuda_11.8/envs/rapids/include main.cpp -o no-pool
$ ./no-pool # completes successfully
$ nvcc -DUSE_POOL -g -O0 -std=c++17 -DFMT_HEADER_ONLY -I $HOME/Documents/src/rapids/rmm/include/ -I $HOME/Documents/src/rapids/compose/etc/conda/cuda_11.8/envs/rapids/include main.cpp -o with-pool
$ ./with-pool 
CUDA Error detected. cudaErrorInvalidResourceHandle invalid resource handle
with-pool: /home/wence/Documents/src/rapids/rmm/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp:253: void rmm::mr::detail::stream_ordered_memory_resource<PoolResource, FreeListType>::do_deallocate(void*, std::size_t, rmm::cuda_stream_view) [with PoolResource = rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource>; FreeListType = rmm::mr::detail::coalescing_free_list; std::size_t = long unsigned int]: Assertion `status__ == cudaSuccess' failed.

```

**Comment by wence-** [comment] 2023-08-30 10:27
At the cost of making RMM dependent on the driver, and not just the runtime, API, this patch fixes the minimal example:
```cpp
#include <cstddef>
#include <memory>
#include <rmm/cuda_stream.hpp>
#include <rmm/cuda_stream_view.hpp>
#include <rmm/device_uvector.hpp>
#include <rmm/mr/device/cuda_memory_resource.hpp>
#include <rmm/mr/device/per_device_resource.hpp>
#include <rmm/mr/device/pool_memory_resource.hpp>
#include <vector>

int main(void) {
  using MemoryResource =
      rmm::mr::pool_memory_resource<rmm::mr::cuda_memory_resource>;

  rmm::mr::cuda_memory_resource general_mr;
  // initializing pool_memory_resource of multiple devices
  int devices = 2;
  std::size_t pool_size = 10240;
  std::vector<std::shared_ptr<MemoryResource>> mrs;

  for (int i = 0; i < devices; ++i) {
    cudaSetDevice(i);
    auto mr = std::make_shared<MemoryResource>(&general_mr, pool_size, pool_size);
    rmm::mr::set_per_device_resource(rmm::cuda_device_id{i}, mr.get());
    mrs.emplace_back(mr);
  }

  {
    cudaSetDevice(0);
    rmm::device_uvector<int> a(10, rmm::cuda_stream_per_thread, mrs[0].get());
    {
      cudaSetDevice(1);
      rmm::device_uvector<int> b(20, rmm::cuda_stream_per_thread, mrs[1].get());
    }
    cudaSetDevice(0);
  }
  return 0;
}
```

Since it is only safe to record events on streams where the contexts match, this change asks the stream for its context, and pushes that context when creating the event. Since we always look up the event by stream, this ensures that the event provided will always be safe to use with the given stream.

```diff
diff --git a/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp b/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp
index 53575e5c..e069fbcc 100644
--- a/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp
+++ b/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp
@@ -22,6 +22,7 @@
 
 #include <fmt/core.h>
 
+#include <cuda.h>
 #include <cuda_runtime_api.h>
 
 #include <cstddef>
@@ -287,13 +288,6 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
    */
   stream_event_pair get_event(cuda_stream_view stream)
   {
-    if (stream.is_per_thread_default()) {
-      // Create a thread-local shared event wrapper. Shared pointers in the thread and in each MR
-      // instance ensures it is destroyed cleaned up only after all are finished with it.
-      thread_local auto event_tls = std::make_shared<event_wrapper>();
-      default_stream_events.insert(event_tls);
-      return stream_event_pair{stream.value(), event_tls->event};
-    }
     // We use cudaStreamLegacy as the event map key for the default stream for consistency between
     // PTDS and non-PTDS mode. In PTDS mode, the cudaStreamLegacy map key will only exist if the
     // user explicitly passes it, so it is used as the default location for the free list
@@ -305,8 +299,12 @@ class stream_ordered_memory_resource : public crtp<PoolResource>, public device_
     auto const iter = stream_events_.find(stream_to_store);
     return (iter != stream_events_.end()) ? iter->second : [&]() {
       stream_event_pair stream_event{stream_to_store};
+      CUcontext stream_ctx;
+      cuStreamGetCtx(stream.value(), &stream_ctx);
+      cuCtxPushCurrent(stream_ctx);
       RMM_ASSERT_CUDA_SUCCESS(
         cudaEventCreateWithFlags(&stream_event.event, cudaEventDisableTiming));
+      cuCtxPopCurrent(&stream_ctx);
       // NOLINTNEXTLINE(cppcoreguidelines-pro-bounds-pointer-arithmetic)
       stream_events_[stream_to_store] = stream_event;
       return stream_event;
```

**Comment by harrism** [comment] 2023-08-30 22:08
OK, thanks for root-causing this @jiajunchang and @wence- . I don't want to mix driver and runtime APIs if we can avoid it. I think instead we should probably switch to the device associated with this MR before recording the event, and then switch back (push and pop), to avoid the error. 

But first I would like to successfully create a failing test that would be fixed by the change. That is what I tried yesterday but failed. Will work on that.

**Comment by wence-** [comment] 2023-08-30 22:12
I think my example in the previous comment should exhibit the issue, but interested if it doesn't for you (I have a 12.0 driver, but tried with both an 11.8 and 12.2 CTK)

**Comment by harrism** [comment] 2023-08-31 02:18
I've figured out that the reason I couldn't reproduce is that I was in a release build. The `RMM_ASSERT_CUDA_SUCCESS(cudaEventRecord(stream_event.event, stream.value()));` of course does not assert in a release build.  

I think that should probably be a RMM_CUDA_TRY since that probably won't affect release performance noticeably, and will catch errors in release builds (as exceptions, not assertions, so potentially non-fatal).

**Comment by harrism** [comment] 2023-08-31 04:59
@wence- I'm not sure your suggestion works with multiple threads. Two threads that both call `get_event()` with the `per_thread_default_stream` will end up sharing the same event: but each thread's PTDS is a different stream, so I don't think that is valid. This is the whole reason for the TLS. Each thread has its own PTDS.  I think I need to make the TLS into a vector of events indexed by device ID.

**Comment by harrism** [comment] 2023-08-31 07:40
@jiajunchang I've opened a PR with a proposed fix. Thanks for submitting this issue, and sorry it took me a while to look into it.

**Closed** 2023-09-13 00:54 UTC
Labels: question, ? - Needs Triage
