### ISSUE TITLE
[BUG]  "__global__ function call is not configured" <- What does this mean?

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/rmm#55] opened 2019-03-13 19:51 UTC
I'm developing a feature over cudf branch-0.6; using rmm changeset dfe2c4b19ad6f55c2c27d75f4d2294c34aff1a39 . At some point, I'm getting this error:
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted
```
This is a problematic exception. Regardless of the reason this happened to me - "system error" is very general, and a typical user of rmm cannot understand what the `what()` message means.

So, please rewrite the code producing this `what()` message to:

* Target people who don't know anything about rmm internals.
* Be more specific in what exactly happened that should not have.
* Describe something which should have been done differently, or was skipped etc. - to give the user a hint regarding how to avoid this exception.
* Add some specifics in addition to the canned string (e.g. address, size, other parameters, other state, or some of the above).

**Comment by jrhemstad** [comment] 2019-03-13 21:16
This is not an RMM exception.

RMM does not yet throw exceptions.

This is a Thrust exception RMM has no control over: `thrust::system::system_error`

We cannot debug further without a minimal reproducer.

**Comment by harrism** [comment] 2019-03-13 21:30
Yes and No. The RMM thrust allocator adater `rmm_allocator` DOES throw this exception, here: https://github.com/rapidsai/rmm/blob/0b273d89a48387d256ad6baf978f74238605c5fd/include/rmm/thrust_rmm_allocator.h#L65

However, the reason given indicates that there is a previous uncaught CUDA error (unconfigured `__global__` function -- that means calling a `__global__` kernel function with improper arguments in `<<<>>>` I think.

I've also seen these errors happen when something messes up the CUDA context --- kernel launch failures due to memory access errors, etc.  Suggest you find which thrust call is failing and debug that.

**Comment by eyalroz** [comment] 2019-03-13 21:45
@harrism : Perhaps it could be a good idea to check for CUDA errors in that adaptor before doing anything else that's CUDA-related, and there is an error, to throw immediately indicating it's a previous error rather than something actually having to do with the allocator?

**Comment by harrism** [comment] 2019-03-13 21:47
I don't think so, because a full check for CUDA errors requires a cudaDeviceSynchronize() to catch errors in unfinished async calls. RMM can't be made synchronous just so it can be the place to catch everybody's CUDA errors.

**Comment by harrism** [comment] 2019-03-18 20:54
I'm going to close this. Feel free to reopen if you find it is indeed an RMM error.

**Closed by harrism** 2019-03-18 20:54 UTC
Labels: bug

**Comment by lmeyerov** [comment] 2019-10-15 22:04
@harrism  Maybe a resurgence...


Kernel: Basically go through a CSV, and for every trailing column not identified in the header, wrap it into an "other" column looking like `"val1,val2,val3"`:

```
def merge_extra_cols(infile, outfile, nrows):
    header = list(pd.read_csv(infile, nrows=2).columns)
    names_long=header + ['c' + str(i) for i in range(0,50)]
    offset=1
    step=int(nrows)
    cols = header
    print('columns: %s' % cols)
    done=False
    while not done:
        print("Step", str(offset))
        try:
            df = cudf.io.read_csv(infile, byte_range=[offset,step], names=names_long)
        except Exception as e:
            print('Done?', e)
            done = True                        
        if len(df) == 0:
            break
        else:
            offset = offset + step
        print('... cleaning...')
        pdf = df.to_pandas()
        pdf2 = pdf.assign(**{
            header[len(header)-1]: pdf[ pdf.columns[len(header) - 1 : len(pdf.columns)] ].apply(
                lambda x: ','.join(x.dropna().astype(str)),
            axis=1)})
        print('... writing batch...')
        pdf2.to_csv(outfile, mode='a', header=False)
    print('done, exiting.') 
```

(Note that the cudf here is just for parsing, not using nvstrings for the concat, as I'm still figuring that one out ;-) )


Output:
```
Step 1
... cleaning...
... writing batch...
Step 301
... cleaning...
... writing batch...
Step 601
... cleaning...
... writing batch...
Step 901
... cleaning...
... writing batch...
Step 1201
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Exn, exiting
```

Weirdly, reproduces in `rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04` but not `rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu18.04` .

**Comment by harrism** [comment] 2019-10-16 00:05
Please file a cuDF issue. RMM does not launch kernels so this cannot be an RMM issue.
