### ISSUE TITLE
[BUG] RMM spits pages of deprecated warnings when building

### ISSUE THREAD

**Issue by gonzalobg** [rapidsai/rmm#551] opened 2020-09-11 07:28 UTC
**Describe the bug and steps to reproduce**

```shell
mkdir build && cd build
cmake .. # options
make -j
```

outputs pages of deprecated warnings due to the use of `[[deprecated]]` APIs in tests.

I can reproduce this with clang and gcc.

**Expected behavior**

The current development branch builds without warnings. Otherwise I need to skim through pages of warnings every time I make a change to verify that I haven't introduced any new issues, which costs me time.

**Environment details (please complete the following information):**
 - Environment location: docker
 - Method of RMM install: source
 - Docker: custom image, no docker pull provided.

**Other**

Possible fix: always test simple build without dependencies on CI, using `-Werror` to prevent this issue from being re-introduced in the future.

**Comment by harrism** [comment] 2020-09-11 11:24
I don't understand why I do not see these warnings locally. Perhaps since you are using clang?

**Comment by gnzlbg** [comment] 2020-09-11 11:59
This is a self contained reproducer: gcc 7.5.0, cuda 11.0:

```shell
git clone https://github.com/rapidsai/rmm.git
cd rmm && mkdir build && cd build
cmake ..
make -j
```

Note that I'm building rmm standalone, no anaconda, cudf, etc.

**Comment by gonzalobg** [comment] 2020-09-11 11:59
This is a self contained reproducer: gcc 7.5.0, cuda 11.0:

```shell
git clone https://github.com/rapidsai/rmm.git
cd rmm && mkdir build && cd build
cmake ..
make -j
```

Note that I'm building rmm standalone, no anaconda, cudf, etc.

**Comment by germasch** [comment] 2020-09-11 12:33
Try this ;):
```
cmake -DDISABLE_DEPRECATION_WARNING=OFF ..
```

**Comment by gonzalobg** [comment] 2020-09-11 13:13
That disables the deprecation warning for the whole project, so that if I accidentally use a deprecated API somewhere, it won't warn.

**Comment by germasch** [comment] 2020-09-11 13:23
That's true of course, but in terms of building rmm by itself, the global options gets the job done.

What exactly is bothering you, the fact that the depreciation warnings trigger in the tests when you're building rmm as part of your own project?

If so, I guess one workaround might to disable building the tests in the first place. But I agree, the proper fix would be to disable the depreciation warnings just for the tests. I think it would be much less invasive to just disable the warnings for the tests by means of `-Wno-deprecated...` being added to (just) the tests build.

**Comment by harrism** [comment] 2020-09-11 22:24
So -Wno-deprecated-declarations either doesn't work with your compiler, or you are not setting it for your own project's files that include RMM headers.

**Comment by harrism** [comment] 2020-09-11 22:24
We also build RMM and libcudf with -Werror, BTW.

**Comment by gonzalobg** [comment] 2020-09-12 08:50
> So -Wno-deprecated-declarations either doesn't work with your compiler, or you are not setting it for your own project's files that include RMM headers.

My reproducer above produces warnings with clang 9, 10, 11, and 12. And gcc 7, 8, 9, and 10. Which compiler are you using for which my reproducer above produces no warnings ? I can try that one.

**Comment by germasch** [comment] 2020-09-12 13:25
@harrism I think what's happening is that @gonzalobg doesn't want to use `DISABLE_DEPRECATION_WARNING=OFF`, because the resulting `-Wno-deprecated-declarations` is indiscriminately applied, to all files being compiled and not just to the depreciation warnings in rmm itself. And without that, he of course does get the warnings.

I think the problem is somewhat minor, in particular if the offending code really gets removed before the next release (But I also think it somewhat defeats the purpose of introducing a depreciation warning to not have persist for at least one release cycle, ie., in 0.15 the API was not yet deprecated, and in 0.16 it'll be gone completely?)

In any case, I could add this to my pending PR #553, which would only disable the depreciation warning in the particular tests that throw it, if that's considered helpful to @gonzalobg . (This doesn't handle `-Xcompiler` for nvcc. It could be added, but it's not currently needed, there are no `.cu` files in rmm)

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e424021..570c7c7 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -49,9 +49,9 @@ option(BUILD_TESTS "Configure CMake to build tests" ON)
 option(BUILD_BENCHMARKS "Configure CMake to build (google) benchmarks" OFF)

 option(DISABLE_DEPRECATION_WARNING "Disable warnings generated from deprecated declarations." OFF)
+add_library(disable_depreciation_warning INTERFACE)
 if(DISABLE_DEPRECATION_WARNING)
-  set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler -Wno-deprecated-declarations")
-  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-deprecated-declarations")
+  target_compile_options(disable_depreciation_warning INTERFACE "-Wno-deprecated-declarations")
 endif(DISABLE_DEPRECATION_WARNING)

 # cudart can be statically linked or dynamically linked the python ecosystem wants dynamic linking
diff --git a/tests/CMakeLists.txt b/tests/CMakeLists.txt
index acc7714..fbce825 100644
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -59,6 +59,7 @@ set(DEVICE_MR_TEST_SRC
     "${CMAKE_CURRENT_SOURCE_DIR}/mr/device/mr_multithreaded_tests.cpp")

 ConfigureTest(DEVICE_MR_TEST "${DEVICE_MR_TEST_SRC}")
+target_link_libraries(DEVICE_MR_TEST disable_depreciation_warning)

 ###################################################################################################
 ###################################################################################################
@@ -77,18 +78,18 @@ set(THRUST_ALLOCATOR_TEST_SRC
     "${CMAKE_CURRENT_SOURCE_DIR}/mr/device/thrust_allocator_tests.cu")

 ConfigureTest(THRUST_ALLOCATOR_TEST "${THRUST_ALLOCATOR_TEST_SRC}")
+target_link_libraries(THRUST_ALLOCATOR_TEST disable_depreciation_warning)

 ###################################################################################################
 ###################################################################################################
 # - device mr per-thread default stream tests------------------------------------------------------

-
 set(DEVICE_MR_PTDS_TEST_SRC
     "${CMAKE_CURRENT_SOURCE_DIR}/mr/device/mr_multithreaded_tests.cpp")

 ConfigureTest(DEVICE_MR_PTDS_TEST "${DEVICE_MR_PTDS_TEST_SRC}")
 target_compile_definitions(DEVICE_MR_PTDS_TEST PUBLIC CUDA_API_PER_THREAD_DEFAULT_STREAM)
-
+target_link_libraries(DEVICE_MR_PTDS_TEST disable_depreciation_warning)

 ###################################################################################################
 ###################################################################################################
```

**Comment by harrism** [comment] 2020-09-13 06:19
In 0.14 it was not yet deprecated. In 0.15 it is deprecated. Since RMM follows SEMVER and is pre-1.0 software I think it's reasonable to remove in 0.16.

**Comment by germasch** [comment] 2020-09-14 00:09
> In 0.14 it was not yet deprecated. In 0.15 it is deprecated. Since RMM follows SEMVER and is pre-1.0 software I think it's reasonable to remove in 0.16.

You're right, @harrism -- I'm sorry, I had checked in my local `branch-0.15`, and it wasn't deprecated there, but it turns out that my `branch-0.15` was out of date with respect to upstream. Because of this, I had assumed that the deprecation was only added after 0.15 was released, that's what my comment was about, but I was wrong.

**Comment by harrism** [comment] 2020-09-14 03:25
No worries, I also realized the reason I don't see all the warnings: I, like a lot of the RAPIDS team, use rapids-compose for development (https://github.com/trxcllnt/rapids-compose/), which has a lot of convenience features designed for our process, and I just noticed that it disables the deprecation warnings.  Sorry about that.

**Comment by gonzalobg** [comment] 2020-09-14 10:57
> No worries, I also realized the reason I don't see all the warnings: I, like a lot of the RAPIDS team, use rapids-compose for development (https://github.com/trxcllnt/rapids-compose/), which has a lot of convenience features designed for our process, and I just noticed that it disables the deprecation warnings.

That makes sense. Does that means that it disables deprecation warnings for the whole project? Does one get a warning under that setup when trying to use C++ APIs that are deprecated (from other libraries, the standard library, etc.) ?

**Comment by harrism** [comment] 2020-09-14 22:31
:man_shrugging:

**Closed** 2020-09-21 02:57 UTC
Labels: ? - Needs Triage, bug
