### ISSUE TITLE
[BUG] Pooled mode leaves CUDA error pending after allocation failure

### ISSUE THREAD

**Issue by jlowe** [rapidsai/rmm#316] opened 2020-02-28 13:46 UTC
**Describe the bug**
When using RMM 0.13 in pooled mode (cnmem backend), allocation failures leave a CUDA error pending.  This causes a subsequent, unrelated CUDA operation to fail with this error.

**Steps/Code to reproduce bug**
Try to allocate a very large amount of memory from RMM in pooled mode, catch the thrown `bad_alloc` exception and check the pending CUDA error with `cudaGetLastError`.

**Expected behavior**
CUDA errors should not be left pending if RMM is itself reporting the error directly via a thrown exception.  RMM in non-pooled mode (direct CUDA allocation) does not leave a CUDA error pending in this same setup.

**Comment by jrhemstad** [comment] 2020-02-28 14:23
Technically this is CNMEM reporting an error and we're just percolating it up. Not all CNMEM errors are CUDA errors, so it doesn't really make sense to clear CUDA errors any time CNMEM reports an error. 

Furthermore, the CNMEM bad_alloc exception isn't telling you what the CUDA error is. Which you could argue is why the CUDA error is left pending for the user to inspect.

**Comment by jlowe** [comment] 2020-02-28 14:27
So then is it a problem that non-pooled mode is clearing the error?  IMO the behavior here should be consistent.

**Comment by jrhemstad** [comment] 2020-02-28 14:57
> So then is it a problem that non-pooled mode is clearing the error? IMO the behavior here should be consistent.

Not quite.

In the case of other resources, RMM is making the CUDA calls directly and we can report when and what CUDA error occurred.

With CNMEM, RMM is calling into another library. RMM can and should tell you when an error occurred in CNMEM (CUDA or otherwise), but I'm not sure if it's RMM's job to further introspect what the error was.

**Comment by jlowe** [comment] 2020-02-28 15:51
In the use-case where I'm seeing this issue, I'm wrapping RMM's default memory resource with another one that can do Java callbacks in order to try to free some memory and retry the allocation.  This wrapper doesn't know, and arguably shouldn't need to know, whether the CNMEM allocator is being used.

If the underlying allocator throws `bad_alloc`, I'm not sure how the wrapping allocator can know whether it should clear the CUDA error.  If it doesn't, the issue reported here occurs even though we were able to free memory and allow the allocation reattempt to succeed.  On the other hand, clearing the error could end up picking up an unrelated error that really should be seen by the application directly.  Is it safe to assume any CUDA error besides `cudaErrorMemoryAllocation` did not come from the underlying allocator?  Those could be left pending but could cause issues on the allocation reattempt if the underlying allocator ends up seeing it.  The wrapping allocator can't throw the error to the application because `RMM_ALLOC` catches all exceptions and returns the `RMM_ERROR_OUT_OF_MEMORY` for all of them.

So I either need the RMM resource allocators to not leave CUDA errors they caused pending when `bad_alloc` is thrown, or `RMM_ALLOC` needs a way to convey CUDA errors to the application that are thrown by the underlying allocator.  CNMEM not letting the caller know whether a CUDA error is pending or not certainly isn't helping.  Alternatively `rmm:alloc` could catch a certain exception type and know that means to return `RMM_ERROR_CUDA_ERROR` instead of `RMM_ERROR_OUT_OF_MEMORY`.

**Comment by jrhemstad** [comment] 2020-02-28 17:51
> The wrapping allocator can't throw the error to the application because RMM_ALLOC catches all exceptions and returns the RMM_ERROR_OUT_OF_MEMORY for all of them.

First off, don't base anything off of `RMM_ALLOC` or `rmm::alloc`. For the reasons you mention (and many others) we'd like to deprecate and remove them along with their corresponding `free` APIs: https://github.com/rapidsai/rmm/issues/302

> The wrapping allocator can't throw the error to the application because RMM_ALLOC catches all exceptions and returns the RMM_ERROR_OUT_OF_MEMORY for all of them.

If you're making a wrapping allocator, I would _strongly_ recommend that you do it by implementing a `device_memory_resource` derived type that can wrap other `device_memory_resources`. For example, see how I did this with [`logging_resource_adaptor`](https://github.com/rapidsai/rmm/blob/f161ca90e45a2f0982fa7222dc99dd8dda859bc0/include/rmm/mr/device/logging_resource_adaptor.hpp#L40) to allow adding logging to any existing resource. 

By making your own wrapping resource, you can catch whatever exception is thrown from the `Upstream` resource and handle it as you see fit.  

I'm not sure that this 100% solves your problem, but let's see how far we get with that idea.

**Comment by jlowe** [comment] 2020-02-28 18:49
> f you're making a wrapping allocator, I would strongly recommend that you do it by implementing a device_memory_resource derived type that can wrap other device_memory_resources

Yes, that is what I've done.  I'm catching the `bad_alloc` but then don't know whether to clear an outstanding CUDA error or not.  I originally did not, just freed some memory and re-attempted the allocation.  That worked great until the next, unrelated CUDA operation noticed the error.  That means I need a way to clean this up without screwing up error states that are not related to the allocation failure.

For now I put in a hack in the allocator that peeks at the CUDA allocation and sees if it's `cudaErrorMemoryAllocation`.  If it is then it assumes, hopefully correctly, the error must have been generated by the allocator, so it clears the error before reattempting the allocation.  Not pretty but effective in practice.

It would be great if there was a better way to know for sure whether a CUDA error was generated by the allocator.  Or better yet, _never leave CUDA errors from allocators_.  It's already throwing errors, and if it's a CUDA error then put that info in the thrown error.  The fact that CNMEM can return without making it very clear whether or not there's a pending CUDA error is baffling to me.

**Comment by jrhemstad** [comment] 2020-02-29 00:53
> I'm catching the `bad_alloc` but then don't know whether to clear an outstanding CUDA error or not.

Yeah, that's the pretty much the same problem we've got in the `cnmem_memory_resource`, but just a layer down the abstraction stack. 

> The fact that CNMEM can return without making it very clear whether or not there's a pending CUDA error is baffling to me.

Well technically I believe it returns a `CNMEM_CUDA_ERROR` or something like that. We'd just need to explicitly check for it and then clear the CUDA error.

**Comment by harrism** [comment] 2020-03-01 21:29
CNMEM returns different errors for OOM vs. other CUDA errors. Other CUDA errors can be either previously uncaught CUDA errors, or caused by incorrect usage, such as passing an invalid stream ID. You should be able to safely call `cudaGetLastError` when you see the former to remove the error state before you retry. The latter is indicative of something really wrong in the app, so you probably don't want to just absorb it, right?

**Comment by jlowe** [comment] 2020-03-02 15:44
Right, it's currently only clearing the error when it is `cudaErrorMemoryAllocation` because that's what the CNMEM-backed resource is leaving pending when it runs out of memory.

I agree that CUDA errors that existed before the allocation should not be cleared by the allocator and instead should be propagated upwards, preferably with a different exception type to make it easier to distinguish on the caller side.  However code should not both throw an exception with details on a CUDA error they caused and also leave the CUDA error pending, IMO.  That forces the caller to deal with the error in two separate ways to recover from it.  Maybe I'm missing the scenario where that type of behavior is desired?

**Comment by harrism** [comment] 2020-03-02 22:15
Agree. All new RMM code that uses the new RMM_CUDA_TRY macros will not leave the CUDA error state. Right @jrhemstad ?

**Comment by jrhemstad** [comment] 2020-03-02 22:22
> Agree. All new RMM code that uses the new RMM_CUDA_TRY macros will not leave the CUDA error state. Right @jrhemstad ?

Correct. The problem is CNMEM doesn't use `RMM_CUDA_TRY`. 

We wrap CNMEM calls in [`CNMEM_TRY`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/cnmem_memory_resource.hpp#L45).

E.g., [`cnmemMalloc`](https://github.com/rapidsai/rmm/blob/branch-0.13/include/rmm/mr/device/cnmem_memory_resource.hpp#L145)

We'd have to introspect the return codes from CNMEM to detect a `CNMEM_STATUS_CUDA_ERROR`, call `cudaGetLastError()` and throw a different kind of exception, which is all kind of awkward.

**Comment by harrism** [comment] 2020-03-02 23:31
I guess I'm unsure what is being proposed to fix this issue...

**Comment by jrhemstad** [comment] 2020-03-03 03:11
> I guess I'm unsure what is being proposed to fix this issue...

I don't really have a clean solution. It's just kind of a mess. 

> We'd have to introspect the return codes from CNMEM to detect a CNMEM_STATUS_CUDA_ERROR, call cudaGetLastError() and throw a different kind of exception, which is all kind of awkward.

This is the best I can come up with, and it's ugly.

**Comment by harrism** [comment] 2020-03-03 03:22
or, we can just wait until we can drop cnmem, if that's OK with @jlowe. :-/

**Comment by jlowe** [comment] 2020-03-03 15:24
I've got a viable workaround, so I'm OK with waiting for the pooled implementation to be replaced with something improved. Thanks for explaining the intricacies and why this isn't so straightforward to fix.

**Comment by harrism** [comment] 2020-03-03 22:32
Thanks @jlowe. Closing for now. Please re-open if it continues to be a problem.

**Closed by harrism** 2020-03-03 22:32 UTC
Labels: bug, wontfix
