### ISSUE TITLE
[FEA] Remove padding completely from `device_memory_resource`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/rmm#1294] opened 2023-06-16 03:02 UTC
Recently, https://github.com/rapidsai/rmm/pull/1278 was merged to remove padding from memory allocators. However, it may not did the job completely. There may still one more place needs to be modified: https://github.com/rapidsai/rmm/blob/0c08dd585031f58e2a9dcfbba5608cce10c423b2/include/rmm/mr/device/arena_memory_resource.hpp#L137-L144

**Comment by ttnghia** [comment] 2023-06-16 03:02
CC @vyasr

**Comment by vyasr** [comment] 2023-06-20 15:40
I mentioned these other appearances of `align_up` in passing in #1278:

> I looked at all other calls to align_up in the library but didn't find any others that needed removing. The other calls all seemed to be used to guarantee specific intentional alignment requirements of other memory resources or adapters. I would appreciate verification from reviewers, though.

In the specific case of the arena memory resource, IIUC if each allocation is not padded then a subsequent allocation from the same mr will be misaligned. We could address this in a different way by manually realigning the subblocks within the arena by checking the integral values of each pointer allocation I think, but I'd want to get @harrism and/or @jrhemstad's take on what the best approach here would be.

FWIW, the arena allocator's approach is immune to the type of overflow noted in #1156 since it's allocating from a pool and can't overflow the available pool size. That doesn't address whether or not padding in this context is still a violation of #865 in a way that we should address, though. IMO I agree that it is still unexpected to see a padded allocation here, it's just more necessary than in the base `device_memory_resource` case.

We also use `align_up` in other MRs like the `aligned_resource_adaptor` and the `binning_resource_adaptor`. In those cases there is again some interplay between alignment and padding (i.e. generating consistently aligned allocations is aided by generating padded allocations). We may want to reconsider those as well.

**Comment by harrism** [comment] 2023-06-20 23:36
@rongou can you comment on the use of `align_up` in `arena_memory_resource`?

**Comment by rongou** [comment] 2023-06-21 00:09
@ttnghia would have more context. My understanding is `cudaMallocAsync` introduced in CUDA 11.2 should have most of the functionality we need for Spark, so perhaps we can deprecate the `arena_memory_resource`.

As for the actual `align_up` call here, since we pre-allocate a pool of memory and divide it up, each suballocation needs to satisfy the cuda malloc contract and align at 256, otherwise I believe we'll get bus errors.

**Comment by harrism** [comment] 2023-06-21 00:13
Yes, it seems we are conflating alignment and padding, which are related but not the same.

**Comment by ttnghia** [comment] 2023-06-21 00:20
@rongou Unfortunately we will need arena allocator for a while, as async allocator is not always available: https://github.com/NVIDIA/spark-rapids/pull/7828.

**Comment by ttnghia** [comment] 2023-06-21 00:33
Close this as we can't do it.

**Comment by vyasr** [comment] 2023-06-21 20:56
Before closing, want to make sure that we're all on the same page regarding what is happening here because as Mark points out we are again close to conflating padding and alignment, in this case in even more confusing ways due to the nature of the pool. My understanding is documented below, please correct me if any of it is incorrect.

The arena allocator allocates a pool of memory from some upstream allocator. Let's assume the base case is that the upstream is `mr::device_memory_resource`. With #1278, the primary allocation owned by the arena is no longer padded. 

When the caller requests memory from the arena mr, it returns subsets of that total allocation to the user. RMM promises that the arena allocator (and all mrs) will conform to CUDA's alignment promises. The pool approach means that for each request the arena finds the first available block that is large enough to satisfy the request, then allocates the requested number of bytes from that block and then puts the remainder of that block back into the list of blocks. The block splitting is not internally padded or aligned in any way. Therefore, getting an aligned allocation here relies on each block already being aligned. In order for that to be true, every allocation request must be padded up to the CUDA alignment requirement (256 bytes) to ensure that the split block that stays in the pool remains aligned. That is the purpose of the `align_up` call that Nghia linked in the issue.

Does that track with everyone's understanding (I've skimmed the arena code, but never really spent time with it). Assuming that is right, the upshot is that in order to ensure alignment of each allocation the allocator is padding each allocation so that the remaining blocks stay aligned. Removing the padding in this case is somewhat pointless because the underlying allocation will still have included the rest of those bytes, and subsequent allocations would still start after those slack bytes. Therefore, there isn't really a point to removing the padding from each allocation. Does that conclusion also track?

**Comment by rongou** [comment] 2023-06-22 01:22
We technically don't need to align the request size. If a single byte is requested, we could theoretically take a free block, remove the first byte, and return the remaining part to the free list. However, this would result in the free block no longer starting at a 256-aligned address. Subsequent allocations would necessitate "chopping off" the beginning until reaching a 256-aligned address. If we return these blocks, which are less than 256 bytes, to the free list, we could end up with many of them, increasing the bookkeeping cost.

To avoid this, we round up the request size to the next multiple of 256. This guarantees that every free block begins with a 256-aligned address, allowing for straightforward allocation from its start.

In the context of memory allocation, we often discuss external versus internal fragmentation. External fragmentation refers to the situation where free memory is fragmented into small blocks scattered throughout the system, caused by the arbitrary order of memory allocation and deallocation. On the other hand, internal fragmentation happens when more memory is allocated to a process than it requested. In our case, not aligning would lead to more external fragmentation. By aligning, we introduce some internal fragmentation. However, as the unused space from internal fragmentation is not usable in any case, it becomes less of an issue.

**Comment by harrism** [comment] 2023-06-22 02:41
The pool MR in RMM does the same.  In fact all MRs that derive from `stream_ordered_memory_resource` comply with CUDA memory allocation alignment by padding the size to a multiple of the CUDA alignment (256).

https://github.com/harrism/rmm/blob/e74a858a8a78c1635c3e3813eb38e4391e58dfa8/include/rmm/mr/device/detail/stream_ordered_memory_resource.hpp#L213

**Comment by vyasr** [comment] 2023-06-29 17:28
Right, I think @rongou is saying exactly the same thing that I am: *padding* a request size is what allows subsequent requests to be *aligned* without any extra work. Any pool approach is going to do the same thing. I don't think any change needs to be made here, just wanted to make sure we clarified this sufficiently for future readers before closing the issue.

**Closed by vyasr** 2023-06-29 17:28 UTC
Labels: feature request, ? - Needs Triage

**Comment by harrism** [comment] 2023-07-04 06:16
:100: I was saying the same thing too, but with code.
