### ISSUE TITLE
[FEA] ARENA allocator should support querying its state

### ISSUE THREAD

**Issue by abellina** [rapidsai/rmm#813] opened 2021-06-25 16:22 UTC
In Spark, when we fail to allocate from ARENA (OOM) we have specialized handling that causes a spill event of a GPU store we use to cache intermediary results.

A common issue we face is we finish cleaning such store (i.e. we have 0 GPU bytes stored), and our own `tracking_memory_resource` says that RMM's pool has plenty of space, but our allocations continue to fail. This leads us to believe there could be fragmentation in the pool, but we have no good way to ask the allocator for its state and print the information (that I know of).

This issue is to add support for a function that returns a data structure with ARENA's state, with at least a "maximum block size" where allocations below this maximum should succeed.

**Comment by harrism** [comment] 2021-07-07 05:04
Querying the maximum available block is likely to require traversing data structures, and therefore could have a cost much higher than the allocation itself. Is that acceptable?

The other thing that troubles me about requests like this is that the `memory_resource` interface does not provide a standard API for such queries. The query and its implementation are very specific to each memory resource (e.g. a `pool_memory_resource` and `arena_memory_resource` have very different data structures). This makes it hard to design a common/standard interface, especially as we are moving to upstream memory_resource into libcudac++.

**Comment by abellina** [comment] 2021-07-08 04:18
> Querying the maximum available block is likely to require traversing data structures, and therefore could have a cost much higher than the allocation itself. Is that acceptable?

Yes, I believe so. I don't think these OOM cases are very hard to reproduce, so one could flip a flag that enables this code path, especially given then penalty as you suggest.

> The other thing that troubles me about requests like this is that the memory_resource interface does not provide a standard API for such queries. The query and its implementation are very specific to each memory resource (e.g. a pool_memory_resource and arena_memory_resource have very different data structures). This makes it hard to design a common/standard interface, especially as we are moving to upstream memory_resource into libcudac++.

I think that a great improvement on what we have now would be to provide this info in `std::bad_alloc` as part of the `what`. I think that a message saying "I couldn't allocate because in stream X your biggest free block was Y", could meet a lot of applications, and this wouldn't require a new interface. Perhaps a flag to the allocator with "verbose errors"?

**Comment by harrism** [comment] 2021-07-08 04:40
Oh, so you don't want a programmatic query interface, just error messages? What will you do, parse them? Or does the human user have to tweak settings based on the error message? The latter doesn't sound like a nice UX.

**Comment by abellina** [comment] 2021-07-08 12:16
I meant in the absence of the programmatic way, given your comment on the upstream work. The log would not be parsed but logged to file.

Getting state on the allocator via an API would be preferable, but if it is really hard to do right now, a log would take us some of the way there.

Tagging @jlowe and @rongou for some feedback on either approach.

**Comment by jlowe** [comment] 2021-07-14 14:23
Apologies for the late reply.

The ask originates from a desire to debug the allocator state at particular times in the application.  For one use-case, we'd like to understand what the state of the allocator is when a (potentially recoverable) OOM is thrown.  Being able to determine the largest allocatable block is only one part of that state.  Ideally we'd like to be able to create a map of GPU memory so we can understand if there is fragmentation, to what degree it exists, and what types of allocations could be triggering it (e.g.: are almost all the blocks causing excessive fragmentation a very similar size?).  I think we can get some of this information somewhat generically through a tracking allocator wrapper, but that may miss subtleties about the specific implementation of the allocator, where it may see a block as generically free but it's not actually available to the current thread due to the current allocator state, or there may be what appears to be a free block in the reconstructed map but it's actually two or more disconnected CUDA-level allocations that we cannot fuse into a single allocation.

Ultimately I think there's two ways to obtain allocator state.  One is generically at a high-level, probably ideally via a tracking allocator wrapper to reconstruct the state by observing the allocator API traffic and using a basic model to understand what may be happening underneath.  Another is to provide an allocator-specific interface that returns very detailed, allocator-specific state information.  Since we're the application and constructed the specific allocator, we can call allocator-specific APIs like this to dump details when desired.  Trying to handle this via a generic memory_resource API is probably going to end up being so generic in the reported state information that a tracking allocator wrapper could reproduce the same info.  The tracking allocator wrapper would be preferable in that case since it is reusable, reduces the implementation requirements of a new memory resource, and only is active when the application desires it.

So I see this issue as an arena-allocator-specific API to dump internal state so an application can emit useful information to diagnose the allocator state.  Without it we can try to emulate it via a tracking wrapper and get most of what we need, but there will be arena allocator state information a tracking allocator cannot reconstruct.

**Comment by harrism** [comment] 2021-07-15 00:47
Yep, I agree it needs to be specific to the allocator.  What you are describing sounds like heap profiling. I've seen various tools attempt to provide a way to visualize the heap over time, and I looked at trying to use something similar in the past, but nothing was easy enough to justify at the time.  Some ideas:

Flame plots: https://www.brendangregg.com/FlameGraphs/memoryflamegraphs.html
Massif: https://www.valgrind.org/docs/manual/ms-manual.html
MTuner: https://github.com/milostosic/MTuner

**Comment by rongou** [comment] 2021-07-31 00:50
We can probably just dump the memory states to the log when an allocation fails, and guard it behind a debug flag. Similar to what tensorflow is doing: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/bfc_allocator.cc#L461

**Comment by rongou** [comment] 2022-01-14 21:54
We now have an option to dump the arena memory state when running out of memory, but it's not exposed on the java/spark side. @abellina @jlowe do you think we should add a new rapids config to expose this?

**Comment by abellina** [comment] 2022-01-14 22:03
It would be nice to have, but I don't know how much time we should spend at this time plumbing it in. That the RMM part has it is great, building cuDF with some debug lines added locally is not that bad so we can expose it for a test. I defer to @jlowe to see if he's more keen on this feature being fully available.

**Comment by jlowe** [comment] 2022-01-14 22:09
>  I defer to @jlowe to see if he's more keen on this feature being fully available.

I think it would be a useful thing to have when devs are trying to debug OOM problems when the ARENA allocator is the backend, but since you two are the ones that tend to be the first-responders to these OOM problems, it seems you would have the most relevant experience on whether you think having this functionality in the RAPIDS Accelerator is a priority or not.

If switching the default to the async allocator soon is realistic then this seems not as important.

**Comment by rongou** [comment] 2022-01-14 22:32
Ok, closing this for now. We can always add the plumbing later if debugging becomes too much of a hassle.

**Closed by rongou** 2022-01-14 22:32 UTC
Labels: feature request, ? - Needs Triage
